version: "3.9"

services:
  web:
    build: .
    container_name: app-web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db
    # Evitar montajes pesados si no son estrictamente necesarios
    # volumes:
    #   - .:/app
    #   - ./.env.local:/app/.env.local

  db:
    image: postgres:15-alpine  # 💡 Usa imagen Alpine, más ligera (~40MB)
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: invoice
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
