services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: invoice_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root  # Idealmente usar variable de entorno segura o .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - invoice_network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env.prod
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: always
    networks:
      - invoice_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  invoice_network:
